# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  # The name defines how the plugin is invoked, A unique name
  name: plugin-weread
spec:
  enabled: true
  requires: ">=2.21.0"
  author:
    name: ytxCells
    website: https://github.com/ytxCells
  logo: logo.png
  homepage: https://github.com/ytxCells/plugin-weread-halo#readme
  repo: https://github.com/ytxCells/plugin-weread-halo
  issues: https://github.com/ytxCells/plugin-weread-halo/issues
  displayName: "微信读书"
  description: "微信读书 - Halo 插件"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/ytxCells/plugin-weread-halo/blob/main/LICENSE"
  configMapName: setting-weread-configmap
  settingName: setting-weread